---

- name: Enable openidm service - CentOS/RHEL 6
  service:
    name: "{{ frim_service_name }}"
    state: restarted
    enabled: "yes"
  when: ansible_distribution_major_version == '6'

- name: Enable openidm service - CentOS/RHEL 7
  service:
    name: "{{ frim_service_name }}.service"
    state: restarted
    enabled: "yes"
  when: ansible_distribution_major_version >= '7'
