---

- name: Install required packages. This takes a while - be patient
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - unzip

- name: create top level software directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ frim_fr_user }}"
    group: "{{ frim_fr_group }}"
    mode: 0755
  loop:
    - "{{ frim_install_path }}"
    - "{{ frim_instance_path }}"
    - "{{ frim_staging_dir }}"

- name: upload staging files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ frim_fr_user }}"
    group: "{{ frim_fr_group }}"
    mode: 0755
  loop:
    - src: "{{ frim_install_file }}"
      dest: "{{ frim_staging_dir }}/openidm.zip"

- name: unarchive
  unarchive:
    src: "{{ frim_staging_dir }}/openidm.zip"
    dest: "{{ frim_staging_dir }}"
    copy: "no"
    list_files: "yes"
    owner: "{{ frim_fr_user }}"
    group: "{{ frim_fr_group }}"
    creates: "{{ frim_staging_dir }}/startup.sh"
  register: archive_contents
