---

- include_tasks: "extract.yml"
  when: frim_install_operation == 'extract' or
        frim_install_operation == 'install'

- include_tasks: "install.yml"
  when: frim_install_operation == 'install'

- include_tasks: "configure.yml"
  when: frim_install_operation == 'configure' or
        frim_install_operation == 'install'

- include_tasks: "enableService.yml"
  when: frim_install_operation == 'enablservice' or
        frim_install_operation == 'install'
